name: project_template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  
  # Network Packages
  dio: ^4.0.4
  internet_connection_checker: ^0.0.1+3

  # Getx Packages
  get: ^4.3.4
  get_it: ^7.2.0

  # Local Storage Packages
  shared_preferences: ^2.0.6
  get_storage: ^2.0.3

  # Images Packages
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0

  # Loader Packages
  modal_progress_hud_nsn: null

  # Forms Packages
  form_field_validator: ^1.1.0

  # Json Packages
  equatable: ^2.0.3
  freezed: ^1.1.0

  # Analysis Packages
  flutter_lints: ^1.0.4

  # Screen Utilities Packages
  flutter_screenutil: ^5.0.0+2

  flutter_launcher_icons: "^0.9.2"
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

dev_dependencies:
  build_runner: ^2.0.4
  

  # flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
